[alias]
new-plugin = [
    "generate",
    "--path",
    "templates/plugin",
    "--destination",
    "plugins",
]
# workspace の members を触られたくないならこれも足す（必要なら）
# new-plugin = ["generate", "--path", "templates/plugin", "--destination", "plugins", "--no-workspace"]
